### ISSUE TITLE
Refactor publication to publisher

### ISSUE THREAD

**Issue by martijn-benjamin** [martijn-benjamin/filtr-api#9]
As we are basically dealing with publishers we should refactor the API to publisher. It's now publication.

**Comment by denzyldick** [comment]
Ah ga ik doen

**Comment by martijn-benjamin** [comment]
Maybe wait a little bit. Major changes coming up. Spare yourself some stashing and merging

**Comment by martijn-benjamin** [comment]
I'll include this one while i'm at it. ok?
